{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "test-app.serviceAccountName" . }}
  labels:
{{ include "test-app.labels" . | indent 4 }}
{{- end -}}
