apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: php-apache
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 32494
  selector:
    run: php-apache
  type: NodePort
status:
  loadBalancer: {}
